(function(){
'use strict';
const $=id=>document.getElementById(id);
let media=[];
let filter='all';
function toast(m,t){window.App?.toast?.(m,t);}
function formatSize(n){const u=['B','KB','MB','GB'];let i=0,v=Number(n||0);while(v>=1024&&i<u.length-1){v/=1024;i++;}return `${v.toFixed(v>=100||i===0?0:1)} ${u[i]}`;}
function typeOf(mime){if(/^image\//.test(mime))return'image';if(/^video\//.test(mime))return'video';if(/^audio\//.test(mime))return'audio';return'other';}
function preview(m){const t=typeOf(m.mime);if(t==='image')return `<div class="media-preview"><img src="${m.url}" alt="" loading="lazy"></div>`;if(t==='video')return `<div class="media-preview"><video src="${m.url}" muted preload="metadata"></video></div>`;if(t==='audio')return `<div class="media-preview"><div class="file-icon">🎵</div></div>`;return `<div class="media-preview"><div class="file-icon">📎</div></div>`;}
function render(){const grid=$('media-library-grid');if(!grid)return;const list=media.filter(m=>filter==='all'||typeOf(m.mime)===filter);if(!list.length){grid.innerHTML='<div class="empty-state">Nenhuma mídia encontrada.</div>';return;}grid.innerHTML=list.map(m=>`<article class="media-card">${preview(m)}<div class="media-info"><strong title="${m.name}">${m.name}</strong><small>${formatSize(m.size)} · ${m.mime}</small></div><div class="media-actions"><button class="btn btn-small" data-use="${m.id}">Enviar</button><a class="btn btn-small" href="${m.url}" target="_blank" rel="noopener">Abrir</a></div></article>`).join('');grid.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{const m=media.find(x=>String(x.id)===String(b.dataset.use));if(m)sendMedia(m);});}
async function load(){try{const r=await fetch('/api/media/library',{credentials:'same-origin'}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha ao carregar mídia.');media=d.media||[];render();}catch(e){toast(e.message,'error');}}
function sendMedia(m){const st=window.App?.getState?.();if(!st?.activeDMUserId&&!st?.activeChannelId)return toast('Abra uma conversa ou canal primeiro.','error');const content='__MEDIA__:'+JSON.stringify({id:m.id,url:m.url,name:m.name,mime:m.mime,size:m.size});const cb=r=>{if(r?.error)toast(r.error,'error');else{window.App?.handleIncomingMessage?.(r.message,st.activeChannelId?'channel':'dm');toast('Mídia enviada.','success');}};if(st.activeChannelId)window.ChatSocket.sendChannelMessage(st.activeChannelId,content,cb);else window.ChatSocket.sendDMMessage(st.activeDMUserId,content,cb);}
function upload(file){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/media/upload');xhr.withCredentials=true;xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.setRequestHeader('X-File-Name',encodeURIComponent(file.name));const bar=$('media-upload-progress'),span=bar?.querySelector('span');bar?.classList.remove('hidden');xhr.upload.onprogress=e=>{if(e.lengthComputable&&span)span.style.width=(e.loaded/e.total*100)+'%';};xhr.onload=()=>{bar?.classList.add('hidden');try{const d=JSON.parse(xhr.responseText||'{}');if(xhr.status>=200&&xhr.status<300)resolve(d.media);else reject(Error(d.error||'Upload falhou.'));}catch(e){reject(Error('Resposta inválida do servidor.'));}};xhr.onerror=()=>{bar?.classList.add('hidden');reject(Error('Falha de conexão durante o upload.'));};xhr.send(file);});}
async function uploadFiles(files){for(const file of files){if(file.size>4*1024*1024*1024){toast(`${file.name} excede 4 GB.`,'error');continue;}try{const m=await upload(file);media.unshift(m);render();sendMedia(m);}catch(e){toast(`${file.name}: ${e.message}`,'error');}}}
function open(){document.getElementById('modal-overlay')?.classList.remove('hidden');$('modal-media')?.classList.remove('hidden');document.querySelectorAll('.modal').forEach(m=>{if(m.id!=='modal-media')m.classList.add('hidden');});load();}
function bind(){ $('media-btn')?.addEventListener('click',open);$('media-upload-btn')?.addEventListener('click',()=>$('media-file-input')?.click());$('media-file-input')?.addEventListener('change',e=>{uploadFiles(e.target.files);e.target.value='';});document.querySelectorAll('[data-media-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.mediaFilter;document.querySelectorAll('[data-media-filter]').forEach(x=>x.classList.toggle('active',x===b));render();}));}
document.addEventListener('DOMContentLoaded',bind);window.WCMedia={open,load,uploadFiles};
})();
