(function(){'use strict';
const $=id=>document.getElementById(id);let canvas,ctx,tool='brush',drawing=false,start=null,history=[],future=[],layers=[],active=0,grid=false,zoom=1;
function toast(m,t){window.App?.toast?.(m,t);}
function initCanvas(){canvas=$('wipaint-canvas');if(!canvas)return;ctx=canvas.getContext('2d',{willReadFrequently:true});layers=[makeLayer('Camada 1')];active=0;renderLayers();resizeCanvas();saveHistory();}
function makeLayer(name){const c=document.createElement('canvas');c.width=canvas.width;c.height=canvas.height;return{name,c,visible:true,opacity:1};}
function resizeCanvas(){if(!canvas)return;canvas.style.transform=`scale(${zoom})`;canvas.style.transformOrigin='top left';render();}
function render(){if(!ctx)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);for(const l of layers){if(!l.visible)continue;ctx.save();ctx.globalAlpha=l.opacity;ctx.drawImage(l.c,0,0);ctx.restore();}if(grid){ctx.save();ctx.globalAlpha=.18;ctx.strokeStyle='#777';ctx.lineWidth=1;for(let x=0;x<canvas.width;x+=16){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke();}for(let y=0;y<canvas.height;y+=16){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke();}ctx.restore();}}
function pos(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)/zoom)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)/zoom))};}
function style(c){const color=$('wipaint-color')?.value||'#fff',size=Number($('wipaint-size')?.value||12),opacity=Number($('wipaint-opacity')?.value||100)/100;c.globalAlpha=opacity;c.lineCap=tool==='pixel'?'butt':'round';c.lineJoin='round';c.lineWidth=tool==='pixel'?Math.max(1,Math.round(size/4))*4:size;c.strokeStyle=color;c.fillStyle=color;}
function snapshot(){return layers.map(l=>({name:l.name,visible:l.visible,opacity:l.opacity,data:l.c.toDataURL('image/png')}));}
function restore(snap){return Promise.all(snap.map(x=>new Promise(res=>{const l=makeLayer(x.name);l.visible=x.visible;l.opacity=x.opacity;const im=new Image();im.onload=()=>{l.c.getContext('2d').drawImage(im,0,0);res(l);};im.src=x.data;}))).then(ls=>{layers=ls;active=Math.min(active,layers.length-1);renderLayers();render();});}
function saveHistory(){history.push(snapshot());if(history.length>30)history.shift();future=[];}
async function undo(){if(history.length<2)return;const cur=history.pop();future.push(cur);await restore(history[history.length-1]);}
async function redo(){const s=future.pop();if(!s)return;history.push(s);await restore(s);}
function commit(){saveHistory();}
function current(){return layers[active];}
function pointerDown(e){if(e.button!==0)return;drawing=true;start=pos(e);if(tool==='eyedropper'){const p=ctx.getImageData(Math.floor(start.x),Math.floor(start.y),1,1).data;$('wipaint-color').value='#'+[p[0],p[1],p[2]].map(x=>x.toString(16).padStart(2,'0')).join('');drawing=false;return;}if(tool==='fill'){const l=current(),c=l.c.getContext('2d');style(c);c.fillStyle=$('wipaint-color').value;c.fillRect(0,0,l.c.width,l.c.height);render();commit();drawing=false;return;}if(tool==='text'){const text=prompt('Texto:');if(text){const l=current(),c=l.c.getContext('2d');style(c);c.font=`${Math.max(12,Number($('wipaint-size').value)*2)}px sans-serif`;c.fillText(text,start.x,start.y);render();commit();}drawing=false;return;}if(tool==='brush'||tool==='pixel'||tool==='eraser'){drawTo(start,start);}}
function drawTo(a,b){const l=current(),c=l.c.getContext('2d');style(c);if(tool==='eraser'){c.globalCompositeOperation='destination-out';}else c.globalCompositeOperation='source-over';if(tool==='pixel'){const s=Math.max(4,Math.round(Number($('wipaint-size').value)/4)*4);c.fillRect(Math.floor(b.x/s)*s,Math.floor(b.y/s)*s,s,s);}else{c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();}c.globalCompositeOperation='source-over';render();}
function pointerMove(e){if(!drawing)return;const p=pos(e);if(tool==='brush'||tool==='pixel'||tool==='eraser')drawTo(start,p);start=p;}
function pointerUp(e){if(!drawing)return;const end=pos(e);if(['line','rect','circle'].includes(tool)){const l=current(),c=l.c.getContext('2d');style(c);c.clearRect(0,0,l.c.width,l.c.height);const base=history[history.length-1];restore(base).then(()=>{const ll=current(),cc=ll.c.getContext('2d');style(cc);const x=start.x,y=start.y,w=end.x-x,h=end.y-y;if(tool==='line'){cc.beginPath();cc.moveTo(x,y);cc.lineTo(end.x,end.y);cc.stroke();}else if(tool==='rect'){cc.strokeRect(x,y,w,h);}else{cc.beginPath();cc.ellipse(x+w/2,y+h/2,Math.abs(w/2),Math.abs(h/2),0,0,Math.PI*2);cc.stroke();}render();commit();});}else commit();drawing=false;start=null;}
function renderLayers(){const box=$('wipaint-layers');if(!box)return;box.innerHTML=layers.map((l,i)=>`<div class="wipaint-layer ${i===active?'active':''}" data-layer="${i}"><button>${l.visible?'👁':'🚫'}</button><span>${l.name}</span></div>`).join('');box.querySelectorAll('[data-layer]').forEach(el=>el.onclick=()=>{active=Number(el.dataset.layer);renderLayers();});box.querySelectorAll('button').forEach((b,i)=>b.onclick=e=>{e.stopPropagation();layers[i].visible=!layers[i].visible;renderLayers();render();});}
function addLayer(){layers.push(makeLayer('Camada '+(layers.length+1)));active=layers.length-1;renderLayers();render();commit();}
function deleteLayer(){if(layers.length<=1)return toast('Mantenha pelo menos uma camada.','error');layers.splice(active,1);active=Math.max(0,active-1);renderLayers();render();commit();}
function clear(){current().c.getContext('2d').clearRect(0,0,canvas.width,canvas.height);render();commit();}
function openFile(){$('wipaint-file-input')?.click();}
function loadImage(file){if(!file)return;const im=new Image();im.onload=()=>{canvas.width=Math.min(1400,im.width);canvas.height=Math.min(1000,im.height);layers=[makeLayer('Imagem')];layers[0].c.width=canvas.width;layers[0].c.height=canvas.height;layers[0].c.getContext('2d').drawImage(im,0,0,canvas.width,canvas.height);active=0;history=[];future=[];renderLayers();render();saveHistory();URL.revokeObjectURL(im.src);};im.src=URL.createObjectURL(file);}
function save(){const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const oc=out.getContext('2d');oc.fillStyle='#fff';oc.fillRect(0,0,out.width,out.height);for(const l of layers){if(l.visible){oc.globalAlpha=l.opacity;oc.drawImage(l.c,0,0);}}const a=document.createElement('a');a.download='wipaint-'+Date.now()+'.png';a.href=out.toDataURL('image/png');a.click();}
function bind(){if(!$('wipaint-open-btn'))return;$('wipaint-open-btn').onclick=()=>{$('modal-overlay')?.classList.remove('hidden');document.querySelectorAll('.modal').forEach(m=>m.classList.add('hidden'));$('modal-wipaint')?.classList.remove('hidden');if(!canvas)initCanvas();};$('wipaint-tool')?.addEventListener('change',e=>tool=e.target.value);$('wipaint-size')?.addEventListener('input',e=>{$('wipaint-size-value').textContent=e.target.value+' px';});$('wipaint-zoom')?.addEventListener('input',e=>{zoom=Number(e.target.value)/100;resizeCanvas();});$('wipaint-undo')?.addEventListener('click',undo);$('wipaint-redo')?.addEventListener('click',redo);$('wipaint-clear')?.addEventListener('click',clear);$('wipaint-grid')?.addEventListener('click',()=>{grid=!grid;render();});$('wipaint-add-layer')?.addEventListener('click',addLayer);$('wipaint-delete-layer')?.addEventListener('click',deleteLayer);$('wipaint-save')?.addEventListener('click',save);$('wipaint-open-image')?.addEventListener('click',openFile);$('wipaint-file-input')?.addEventListener('change',e=>loadImage(e.target.files?.[0]));canvas?.addEventListener('pointerdown',pointerDown);canvas?.addEventListener('pointermove',pointerMove);window.addEventListener('pointerup',pointerUp);}
document.addEventListener('DOMContentLoaded',bind);window.WiPaint={open:openFile};})();
